import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/Navbar";
import { NextAuthProvider } from "@/components/provider";
import NavbarBottom from "@/components/navbar";
import { TooltipProvider } from "@/components/ui/tooltip";
import { ThemeProvider } from "@/components/theme-provider";
import BlurFade from "@/components/magicui/blur-fade";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "vivek sarkar portfolio",
  description: "Generated by create next app",
};
const BLUR_FADE_DELAY = 0.04;
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeProvider attribute="class" defaultTheme="light">
      <TooltipProvider delayDuration={0}>
      <BlurFade delay={BLUR_FADE_DELAY }>
      <Navbar />
      </BlurFade>
       
        <NavbarBottom/>
        <NextAuthProvider>{children}</NextAuthProvider>
        </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
